# Generated by Django 3.2.9 on 2022-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_transaction_amount_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default="lala", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="retailer",
            name="slug",
            field=models.CharField(default="lala", max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="category_unique_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("slug", "user"), name="category_unique_slug_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="retailer",
            constraint=models.UniqueConstraint(
                fields=("name", "user"), name="retailer_unique_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="retailer",
            constraint=models.UniqueConstraint(
                fields=("slug", "user"), name="retailer_unique_slug_per_user"
            ),
        ),
    ]
